[categories.apps]
name = "Apps and Software"
short_description = "Mobile, desktop, and web applications and games"
fieldsets = ["software"]
name_field = "software.name"
description_field = "software.description"
featured_fields = ["software.name", "software.platform", "software.accessibility_rating", "software.free_or_paid"]

[categories.reading_apps]
name = "eBook and audiobook apps"
short_description = "Apps for reading ebooks and listening to audiobooks"
parent = "apps"

[categories.games]
name = "Games"
parent = "apps"

[categories.blindness_apps]
name = "Independent Living"
short_description = "Apps that help blind people with independent living"
parent = "apps"

[categories.financial_apps]
name = "Finance and Banking"
short_description = "Apps for banking, stock trading, and personal finance"
parent = "apps"

[categories.social_and_communication_apps]
name = "Social Networking and Communication"
parent = "apps"

[categories.enterprise_apps]
name = "Work and Collaboration"
short_description = "Software typically used for work or to collaborate with others"
parent = "apps"

[categories.screen_readers]
name = "Screen Readers"
short_description = "Screen readers"
parent = "apps"

[categories.navigation_apps]
name = "Navigation"
short_description = "Apps that help with GPS navigation, mobility, and public transit"
parent = "apps"

[categories.players]
name = "Music and Media"
short_description = "Software for playing and streaming music or videos"
parent = "apps"

[categories.audio_apps]
name = "Audio Apps"
short_description = "Audio editors, DAWs, music-making software and plugins"
parent = "apps"

[categories.education_apps]
name = "Education"
parent = "apps"

[categories.productivity_apps]
name = "Productivity"
short_description = "Writing, note-taking, and personal productivity apps"
parent = "apps"

[categories.programming_and_system_administration]
name = "Programming and System Administration"
short_description = "Apps often used for programming, database and cloud management, text console access, and other tasks requiring technical expertise"
parent = "apps"

[categories.other_apps]
short_description = "Software that doesn't fit in other categories"
parent = "apps"

[fieldsets.software]
name = "Basic information about this application"

[[fields.software]]
name = "name"
label = "Application Name"
type = "short-text"

[[fields.software]]
name = "description"
label = "Application Description"
type = "textarea"
description = "A short description of what the app is for"

[[fields.software]]
name = "platform"
label = "Operating System"
type = "dropdown"
options = [
    "Windows",
    "iOS",
    "Android",
    "Web",
    "Linux",
    "Watch OS",
    "TV OS (Apple TV)",
    "Chrome OS",
    "PlayStation",
    "Xbox",
    "Web OS (LG TVs)",
    "Tizen (Samsung TVs)",
]

[[fields.software]]
name = "download_url"
label = "Download or Purchase URL"
type = "url"

[[fields.software]]
name = "developer"
label = "Developer"
type = "short-text"

[[fields.software]]
name = "free_or_paid"
label = "Is this software free or paid?"
type = "radio-buttons"
options = ["Free", "Paid"]

[[fields.software]]
name = "price"
label = "Price"
type = "short-text"
description = "If this software is paid, how much does it cost?"
optional = true

[[fields.software]]
name = "accessibility_rating"
label = "Accessibility Rating"
type = "radio-buttons"
options = ["Completely inaccessible", "Mostly inaccessible", "Has accessibility issues", "Fully accessible"]

[[fields.software]]
name = "accessibility_approach"
label = "Approach to Accessibility"
description = "How does the developer of this app approach accessibility?"
type = "radio-buttons"
options = [
    "Not known",
    "The app is made for the blind or with the blind in mind",
    "The developers care about blind users and fix issues quickly",
    "The developers seem to care, but issues take a while to fix and are sometimes left unfixed",
    "The developers claim that they care, but accessibility issues are rarely ever fixed",
    "The developers have repeatedly ignored accessibility feedback"
]

[[fields.software]]
name = "accessibility_issues"
label = "Accessibility Issues"
description = "What accessibility issues does this app have, if any?"
type = "textarea"

[categories.appliances]
name = "Household Appliances"
short_description = "Microwaves, coffee machines, and other household appliances"
fieldsets = ["physical_product", "appliance"]
featured_fields = ["physical_product.model", "physical_product.price", "appliance.accessibility_rating"]
name_field = "physical_product.model"
description_field = "physical_product.description"

[categories.microwaves]
name = "Microwaves"
parent = "appliances"

[categories.coffee_machines]
name = "Coffee Machines"
parent = "appliances"

[categories.stoves]
name = "Gas and Induction Stoves"
parent = "appliances"

[categories.kitchen_appliances]
name = "Kitchen Appliances"
short_description = "Other appliances used for preparing food"
parent = "appliances"

[categories.washers_and_dryers]
name = "Washers and Dryers"
parent = "appliances"

[fieldsets.physical_product]
name = "Basic product information"

[[fields.physical_product]]
name = "model"
label = "Model Name"
type = "short-text"

[[fields.physical_product]]
name = "description"
label = "Product Description"
type = "textarea"

[[fields.physical_product]]
name = "price"
label = "Price"
type = "short-text"

[[fields.physical_product]]
name = "purchase_url"
label = "Purchase URL"
type = "url"

[fieldsets.appliance]
name = "Appliance-specific information"

[[fields.appliance]]
name = "accessibility_rating"
label = "Accessibility Rating"
type = "radio-buttons"
options = [
    "Fully accessible",
    "Can be used with issues",
    "Barely accessible",
    "Completely inaccessible"
]

[[fields.appliance]]
name = "accessibility_issues"
label = "Accessibility Issues"
type = "textarea"

[[fields.appliance]]
name = "talks"
label = "Does the device provide spoken announcements?"
type = "checkbox"

[[fields.appliance]]
name = "controls"
label = "Controls used?"
type = "radio-buttons"
options = [
    "Physical buttons",
    "Touch sensors requiring significant pressure",
    "Touch sensors that activate even for soft touches",
    "A full touch screen, e.g., one supporting scrolling and multiple menu levels"
]

[[fields.appliance]]
name = "control_layout"
label = "Control Layout"
description = "If possible, please describe how the controls are laid out"
type = "textarea"
optional = true
